use test_db;

insert into t_categoria value(1, 'Estilos personales',1,'¿Se parece a mi?',1);
insert into t_categoria value(2, 'Actividades de preferencia',1,'¿Soy habil?',1);
insert into t_categoria value(3, 'Percepción de habilidad',1,'¿Me interesa?',1);

insert into t_vocacion value (1, 'Liderazgo', 1);
insert into t_vocacion value (2, 'Tecnico mecanico', 1);
insert into t_vocacion value (3, 'Social', 1);
insert into t_vocacion value (4, 'Organizado', 1);
insert into t_vocacion value (5, 'Artistico', 1);
insert into t_vocacion value (6, 'Emprendedor', 1);
insert into t_vocacion value (7, 'Investigativo', 1);

-- id, nombre, id_vocacion, estado
insert into t_carrera value (not null, 'Derecho', 1, 1);
insert into t_carrera value (not null, 'Contabilidad', 1, 1);
insert into t_carrera value (not null, 'PNP', 1, 1);
insert into t_carrera value (not null, 'Fuerzas Armadas', 1, 1);
insert into t_carrera value (not null, 'Ing. Civil', 1, 1);
insert into t_carrera value (not null, 'Arquitectura', 1, 1);
insert into t_carrera value (not null, 'Administracion', 1, 1);
insert into t_carrera value (not null, 'Economia', 1, 1);
insert into t_carrera value (not null, 'Marketing', 1, 1);
insert into t_carrera value (not null, 'Aviacion', 1, 1);
insert into t_carrera value (not null, 'Ing. de Sistemas', 2, 1);
insert into t_carrera value (not null, 'Ing. Electrica', 2, 1);
insert into t_carrera value (not null, 'Ing. Industrial', 2, 1);
insert into t_carrera value (not null, 'Ing. Ambiental', 2, 1);
insert into t_carrera value (not null, 'Ing. de Sonido', 2, 1);
insert into t_carrera value (not null, 'Tec. en Informatica', 2, 1);
insert into t_carrera value (not null, 'Mecanica Automotriz', 2, 1);
insert into t_carrera value (not null, 'Operador de Maquinarias Pesadas', 2, 1);
insert into t_carrera value (not null, 'Soldadura', 2, 1);
insert into t_carrera value (not null, 'Industrial', 2, 1);
insert into t_carrera value (not null, 'Topografia', 2, 1);
insert into t_carrera value (not null, 'Metalurgia', 2, 1);
insert into t_carrera value (not null, 'Aviacion', 2, 1);
insert into t_carrera value (not null, 'Medicina', 3, 1);
insert into t_carrera value (not null, 'Enfermeria', 3, 1);
insert into t_carrera value (not null, 'Obstetricia', 3, 1);
insert into t_carrera value (not null, 'Psicologia', 3, 1);
insert into t_carrera value (not null, 'Educacion', 3, 1);
insert into t_carrera value (not null, 'Veterinaria', 3, 1);
insert into t_carrera value (not null, 'Asistente Social', 3, 1);
insert into t_carrera value (not null, 'Sociologia', 3, 1);
insert into t_carrera value (not null, 'Pedagogia', 3, 1);
insert into t_carrera value (not null, 'Arqueologia', 3, 1);
insert into t_carrera value (not null, 'Historia', 3, 1);
insert into t_carrera value (not null, 'Guia Oficial de Turismo', 3, 1);
insert into t_carrera value (not null, 'C. Comunicacion', 3, 1);
insert into t_carrera value (not null, 'Arquitectura', 3, 1);
insert into t_carrera value (not null, 'Tec. en Linguistica y Almacen', 4, 1);
insert into t_carrera value (not null, 'Administracion', 4, 1);
insert into t_carrera value (not null, 'Contabilidad', 4, 1);
insert into t_carrera value (not null, 'Negocios Internacionales', 4, 1);
insert into t_carrera value (not null, 'Guia Oficial de Turismo', 4, 1);
insert into t_carrera value (not null, 'Economia', 4, 1);
insert into t_carrera value (not null, 'Marketing', 4, 1);
insert into t_carrera value (not null, 'Diseño de Interiores', 5, 1);
insert into t_carrera value (not null, 'Arquitectura', 5, 1);
insert into t_carrera value (not null, 'Cosmetologia', 5, 1);
insert into t_carrera value (not null, 'Profesional Artistico Musico', 5, 1);
insert into t_carrera value (not null, 'Artes Visuales', 5, 1);
insert into t_carrera value (not null, 'Artes Plasticas', 5, 1);
insert into t_carrera value (not null, 'Actuacion', 5, 1);
insert into t_carrera value (not null, 'Gastronomia', 5, 1);
insert into t_carrera value (not null, 'Diseño Grafico', 5, 1);
insert into t_carrera value (not null, 'Dibujo y Pintura', 5, 1);
insert into t_carrera value (not null, 'Marketing', 5, 1);
insert into t_carrera value (not null, 'Ing. de Sonido', 5, 1);
insert into t_carrera value (not null, 'Marketing', 6, 1);
insert into t_carrera value (not null, 'Administracion', 6, 1);
insert into t_carrera value (not null, 'Economia', 6, 1);
insert into t_carrera value (not null, 'Contabilidad', 6, 1);
insert into t_carrera value (not null, 'Astronomia', 6, 1);
insert into t_carrera value (not null, 'Biologia', 7, 1);
insert into t_carrera value (not null, 'Quimica', 7, 1);
insert into t_carrera value (not null, 'Fisica', 7, 1);
insert into t_carrera value (not null, 'Matematica', 7, 1);
insert into t_carrera value (not null, 'Farmacia', 7, 1);
insert into t_carrera value (not null, 'Tec. en Laboratorio', 7, 1);
insert into t_carrera value (not null, 'Publicista', 7, 1);

-- a
insert into t_pregunta value (not null, 'Es un buen lider, sabe como dirigir a las personas',1,1,1);
insert into t_pregunta value (not null, 'Es habil para relacionarse con otras personas',1,1,1);
insert into t_pregunta value (not null, 'Organiza a sus compañeros para realizar diversas actividades',1,1,1);
insert into t_pregunta value (not null, 'Es timido en sus relaciones sociales',1,1,1);
insert into t_pregunta value (not null, 'Convence a sus compañeros o profesores para lograr algo',1,1,1);
insert into t_pregunta value (not null, 'Dirige los grupos en los que trabaja',1,1,1);
insert into t_pregunta value (not null, 'Tiene curiosidad por saber cómo funciona un objeto a máquina',2,1,1);
insert into t_pregunta value (not null, 'Se da cuenta fácilmente de como armar o desarmar objetos',2,1,1);
insert into t_pregunta value (not null, 'Suele reparar artefactos u objetos del hogar ',2,1,1);
insert into t_pregunta value (not null, 'Es bueno para descubrir cómo funciona una herramienta o aparato',2,1,1);
insert into t_pregunta value (not null, 'Es comprensivo fronte a las necesidades de los demás.',3,1,1);
insert into t_pregunta value (not null, 'Coopera con las personas con las que hace algo. ',3,1,1);
insert into t_pregunta value (not null, 'Tiene curiosidad por aprender nuevas cosas',3,1,1);
insert into t_pregunta value (not null, 'Es servicial, ayuda a los demás',3,1,1);
insert into t_pregunta value (not null, 'Es organizado para hacer las cosas',4,1,1);
insert into t_pregunta value (not null, 'Es ordenado, planifica sus acciones',4,1,1);
insert into t_pregunta value (not null, 'Sigue un método ordenado para realizar sus actividades',4,1,1);
insert into t_pregunta value (not null, 'Mantiene ordenados sus útiles, trabajos, presentaciones',4,1,1);
insert into t_pregunta value (not null, 'Es disciplinado en sus actividades',4,1,1);
insert into t_pregunta value (not null, 'Se propone hacer un horario para hacer sus tareas con anticipación',4,1,1);
insert into t_pregunta value (not null, 'Es creativo, con capacidad para crear o inventar algo',5,1,1);
insert into t_pregunta value (not null, 'Es bueno para hacer alguna actividad artística (actuar, dibujar, manualidades, cocinar, etc.)',5,1,1);
insert into t_pregunta value (not null, 'Dedica el tiempo a alguna actividad artística (Cantar, bailar, actuar, dibujar, manualidades, cocinar, etc.)',5,1,1);
insert into t_pregunta value (not null, 'Disfruta de las actividades en donde puede utilizar su imaginación.',5,1,1);
insert into t_pregunta value (not null, 'Se esfuerza por terminar exitosamente sus tareas',6,1,1);
insert into t_pregunta value (not null, 'Es estudioso, intelectual.',6,1,1);
insert into t_pregunta value (not null, 'Es persistente en las tareas que realiza',6,1,1);
insert into t_pregunta value (not null, 'Cuando tiene que hacer una tarea, trata de hacer más de lo que le piden',6,1,1);
insert into t_pregunta value (not null, 'Trata de hacer sus tareas o trabajos lo mejor posible',6,1,1);
insert into t_pregunta value (not null, 'Cuando hace un trabajo revisa con cuidado los detalles',6,1,1);
insert into t_pregunta value (not null, 'Se responsabiliza por alcanzar las metas que se plantea',6,1,1);
insert into t_pregunta value (not null, 'Pone mucha energía para lograr lo que se propone',6,1,1);
