# Generated by Django 4.1.1 on 2022-11-26 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tcolegio',
            options={'permissions': (('mispermisos_view_tcolegio', 'Puede ver las colegios'), ('mispermisos_add_tcolegio', 'Puede agregar colegios'), ('mispermisos_change_tcolegio', 'Puede editar colegios'), ('mispermisos_delete_tcolegio', 'Puede eliminar colegios'))},
        ),
        migrations.AlterModelOptions(
            name='tusuario',
            options={'permissions': (('mispermisos_view_tusuario', 'Puede ver los usuarios'), ('mispermisos_add_tusuario', 'Puede agregar usuarios'), ('mispermisos_change_tusuario', 'Puede editar usuarios'), ('mispermisos_delete_tusuario', 'Puede eliminar usuarios'))},
        ),
    ]
