# Generated by Django 4.1.1 on 2022-12-17 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('panel_admin', '0002_alter_tcolegio_options_alter_tusuario_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcolegio',
            name='usuario',
            field=models.ForeignKey(blank=True, db_column='usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tusuario',
            name='usuario',
            field=models.ForeignKey(blank=True, db_column='usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='tcolegio',
            table=None,
        ),
        migrations.AlterModelTable(
            name='tusuario',
            table=None,
        ),
    ]
