# Generated by Django 4.1.1 on 2022-12-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_admin', '0003_tcolegio_usuario_tusuario_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcolegio',
            name='logo_colegio',
            field=models.ImageField(blank=True, null=True, upload_to='logos_colegio/'),
        ),
    ]
